[project]
site_name = "PureData Ecosystem"
site_url = "https://charlesneimog.github.io/Awesome-Pd/"
docs_dir = "docs"
repo_url = "https://github.com/charlesneimog/Awesome-Pd"
extra_javascript = [
    "js/objects.js",
]
extra_css = [
    "stylesheets/extra.css",
]
not_in_nav = """
/todo.md
/prompts/helppatchai.md
/objects/**/*.md
"""

[project.extra]
head = [
    "<link rel=\"preload\" href=\"../submit-external/index.html\" as=\"document\">",
]

[project.theme]
logo = "assets/icon.svg"
language = "en"
variant = "modern"
features = [
    "navigation.indexes",
    "navigation.instant",
    "navigation.tabs",
    "navigation.path",
    "search.highlight",
    "search.share",
    "search.suggest",
    "toc.integrate",
    "header.autohide",
    "toc.follow",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"

[project.theme.palette.toggle]
icon = "material/brightness-auto"
name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "white"
accent = "light blue"

[project.theme.palette.toggle]
icon = "material/lightbulb"
name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
accent = "light blue"
primary = "black"

[project.theme.palette.toggle]
icon = "material/lightbulb-outline"
name = "Switch to light mode"

[project.theme.icon]
annotation = "material/plus-circle"

[[project.nav]]
Home = "index.md"

[[project.nav]]
Submit = "submit.md"

[[project.nav]]
"Objects & Abstractions" = [
    "objects/index.md",
    { AI = [
    { "Deep Learning" = [
    "objects/deep_learning/index.md",
] },
    { "Machine Learning" = [
    "objects/machine_learning/index.md",
] },
    { "Neural Networks" = [
    "objects/neural_networks/index.md",
] },
    { "Statistical Models" = [
    "objects/statistical_models/index.md",
] },
] },
    { "Analysis / Transform" = [
    { FFT = [
    "objects/fft/index.md",
] },
    { "Spectral Processing" = [
    "objects/spectral_processing/index.md",
] },
    { Wavelets = [
    "objects/wavelets/index.md",
] },
] },
    { Composition = [
    { Algorithmic = [
    "objects/algorithmic/index.md",
] },
    { Procedural = [
    "objects/procedural/index.md",
] },
    { Score-based = [
    "objects/score-based/index.md",
] },
    { "Stochastic / Probabilistic" = [
    "objects/stochastic___probabilistic/index.md",
] },
] },
    { Control = [
    { Envelopes = [
    "objects/envelopes/index.md",
] },
    { LFOs = [
    "objects/lfos/index.md",
] },
    { Logic = [
    "objects/logic/index.md",
] },
    { MIDI = [
    "objects/midi/index.md",
] },
    { Math = [
    "objects/math/index.md",
] },
    { Routing = [
    "objects/routing/index.md",
] },
    { Sequencers = [
    "objects/sequencers/index.md",
] },
] },
    { Effects = [
    { "Chorus/Flanger/Phaser" = [
    "objects/chorus_flanger_phaser/index.md",
] },
    { Delay = [
    "objects/delay/index.md",
] },
    { Distortion = [
    "objects/distortion/index.md",
] },
    { Dynamics = [
    "objects/dynamics/index.md",
] },
    { Filters = [
    "objects/filters/index.md",
] },
    { Reverb = [
    "objects/reverb/index.md",
] },
] },
    { "I/O" = [
    { "Audio I/O" = [
    "objects/audio_i_o/index.md",
] },
    { "Control I/O" = [
    "objects/control_i_o/index.md",
] },
    { "File I/O" = [
    "objects/file_i_o/index.md",
] },
    { Networking = [
    "objects/networking/index.md",
] },
    { OSC = [
    "objects/osc/index.md",
] },
] },
    { Interfaces = [
    { GUI = [
    "objects/gui/index.md",
] },
    { Graphics = [
    "objects/graphics/index.md",
] },
] },
    { "MIR / Analysis" = [
    { Descriptors = [
    "objects/descriptors/index.md",
] },
    { "Partial Tracking" = [
    "objects/partial_tracking/index.md",
] },
    { "Score Follower" = [
    "objects/score_follower/index.md",
] },
] },
    { Plugins = [
    { LADSPA = [
    "objects/ladspa/index.md",
] },
    { "VST2/VST3" = [
    "objects/vst2_vst3/index.md",
] },
] },
    { Scripting = [
    { Lua = [
    "objects/lua/index.md",
] },
    { Python = [
    "objects/python/index.md",
] },
] },
    { Spatialization = [
    { Ambisonics = [
    "objects/ambisonics/index.md",
] },
    { Binaural = [
    "objects/binaural/index.md",
] },
    { VBAP = [
    "objects/vbap/index.md",
] },
] },
    { Synthesis = [
    { Additive = [
    "objects/additive/index.md",
] },
    { Granular = [
    "objects/granular/index.md",
] },
    { Oscillators = [
    "objects/oscillators/index.md",
] },
    { "Physical Modeling" = [
    "objects/physical_modeling/index.md",
] },
    { Samplers = [
    "objects/samplers/index.md",
] },
    { "Spectral / Resynthesis" = [
    "objects/spectral___resynthesis/index.md",
] },
    { Stochastic = [
    "objects/stochastic/index.md",
] },
    { Subtractive = [
    "objects/subtractive/index.md",
] },
] },
    { Uncategorized = [
    "objects/uncategorized/index.md",
] },
    { Utilities = [
    { "Data Structures" = [
    "objects/data_structures/index.md",
] },
    { Debugging = [
    "objects/debugging/index.md",
] },
    { "General Utilities" = [
    "objects/general_utilities/index.md",
] },
    { MultiThreading = [
    "objects/multithreading/index.md",
] },
    { Multichannel = [
    "objects/multichannel/index.md",
] },
    { Patching = [
    "objects/patching/index.md",
] },
    { Text = [
    "objects/text/index.md",
] },
] },
]

[[project.nav]]
Libraries = [
    "libraries/index.md",
    { AutoPreset = "libraries/AutoPreset.md" },
    { Cream = "libraries/Cream.md" },
    { DEAPd = "libraries/DEAPd.md" },
    { DRFX = "libraries/DRFX.md" },
    { FluidCorpusManipulation = "libraries/FluidCorpusManipulation.md" },
    { Fraise = "libraries/Fraise.md" },
    { Gem = "libraries/Gem.md" },
    { Jamoma = "libraries/Jamoma.md" },
    { PDNAM = "libraries/PDNAM.md" },
    { Pd_Spectral_Toolkit = "libraries/Pd_Spectral_Toolkit.md" },
    { RabbitControl = "libraries/RabbitControl.md" },
    { Websockets = "libraries/Websockets.md" },
    { "abl_link~" = "libraries/abl_link~.md" },
    { absattr = "libraries/absattr.md" },
    { aconnect = "libraries/aconnect.md" },
    { acre = "libraries/acre.md" },
    { acre-amb = "libraries/acre-amb.md" },
    { acre-wg = "libraries/acre-wg.md" },
    { adaptive = "libraries/adaptive.md" },
    { "algo~" = "libraries/algo~.md" },
    { aoo = "libraries/aoo.md" },
    { apple = "libraries/apple.md" },
    { array-abs = "libraries/array-abs.md" },
    { arraysize = "libraries/arraysize.md" },
    { art_net = "libraries/art_net.md" },
    { artnetlib = "libraries/artnetlib.md" },
    { asdf = "libraries/asdf.md" },
    { audiolab = "libraries/audiolab.md" },
    { automatonism = "libraries/automatonism.md" },
    { bandlimited = "libraries/bandlimited.md" },
    { bassemu = "libraries/bassemu.md" },
    { bela = "libraries/bela.md" },
    { bf-pd = "libraries/bf-pd.md" },
    { binfile = "libraries/binfile.md" },
    { boids = "libraries/boids.md" },
    { bsaylor = "libraries/bsaylor.md" },
    { bytestruct = "libraries/bytestruct.md" },
    { ceammc = "libraries/ceammc.md" },
    { chair = "libraries/chair.md" },
    { chaos = "libraries/chaos.md" },
    { cicmtools = "libraries/cicmtools.md" },
    { clk = "libraries/clk.md" },
    { command = "libraries/command.md" },
    { comport = "libraries/comport.md" },
    { "constantq~" = "libraries/constantq~.md" },
    { context = "libraries/context.md" },
    { creb = "libraries/creb.md" },
    { cxc = "libraries/cxc.md" },
    { cyclone = "libraries/cyclone.md" },
    { dnd-plugin = "libraries/dnd-plugin.md" },
    { doublechord-plugin = "libraries/doublechord-plugin.md" },
    { dw_lib = "libraries/dw_lib.md" },
    { easyflow = "libraries/easyflow.md" },
    { ekext = "libraries/ekext.md" },
    { else = "libraries/else.md" },
    { ext13 = "libraries/ext13.md" },
    { extra = "libraries/extra.md" },
    { ezaoo = "libraries/ezaoo.md" },
    { "faustgen~" = "libraries/faustgen~.md" },
    { fd_lib = "libraries/fd_lib.md" },
    { fftease = "libraries/fftease.md" },
    { filemtime = "libraries/filemtime.md" },
    { flatgui = "libraries/flatgui.md" },
    { flite = "libraries/flite.md" },
    { flucoma = "libraries/flucoma.md" },
    { "freeverb~" = "libraries/freeverb~.md" },
    { gem2pdp = "libraries/gem2pdp.md" },
    { ggee = "libraries/ggee.md" },
    { "gigaverb~" = "libraries/gigaverb~.md" },
    { gpmotion = "libraries/gpmotion.md" },
    { grainflow = "libraries/grainflow.md" },
    { guis = "libraries/guis.md" },
    { hcs = "libraries/hcs.md" },
    { hexloader = "libraries/hexloader.md" },
    { hid = "libraries/hid.md" },
    { hidin = "libraries/hidin.md" },
    { hidio = "libraries/hidio.md" },
    { hidraw = "libraries/hidraw.md" },
    { "hrtf~" = "libraries/hrtf~.md" },
    { iem16 = "libraries/iem16.md" },
    { iem_ambi = "libraries/iem_ambi.md" },
    { iem_bin_ambi = "libraries/iem_bin_ambi.md" },
    { iem_delay = "libraries/iem_delay.md" },
    { iem_dp = "libraries/iem_dp.md" },
    { iem_roomsim = "libraries/iem_roomsim.md" },
    { iem_spec2 = "libraries/iem_spec2.md" },
    { iem_tab = "libraries/iem_tab.md" },
    { iem_vanilla = "libraries/iem_vanilla.md" },
    { iemgui = "libraries/iemgui.md" },
    { iemguts = "libraries/iemguts.md" },
    { iemlib = "libraries/iemlib.md" },
    { iemmatrix = "libraries/iemmatrix.md" },
    { iemnet = "libraries/iemnet.md" },
    { iempluginOSC = "libraries/iempluginOSC.md" },
    { iemxmlrpc = "libraries/iemxmlrpc.md" },
    { jackpatch = "libraries/jackpatch.md" },
    { jasch_lib = "libraries/jasch_lib.md" },
    { jit_expr = "libraries/jit_expr.md" },
    { jl = "libraries/jl.md" },
    { jmmmp = "libraries/jmmmp.md" },
    { jpcvisu = "libraries/jpcvisu.md" },
    { jsobj = "libraries/jsobj.md" },
    { la-kitchen = "libraries/la-kitchen.md" },
    { leapmotion = "libraries/leapmotion.md" },
    { list-abs = "libraries/list-abs.md" },
    { log = "libraries/log.md" },
    { lolPd = "libraries/lolPd.md" },
    { lyonpotpourri = "libraries/lyonpotpourri.md" },
    { mapping = "libraries/mapping.md" },
    { markex = "libraries/markex.md" },
    { "martha~" = "libraries/martha~.md" },
    { maxlib = "libraries/maxlib.md" },
    { mc = "libraries/mc.md" },
    { mediasettings = "libraries/mediasettings.md" },
    { midifile = "libraries/midifile.md" },
    { "missive~" = "libraries/missive~.md" },
    { mjlib = "libraries/mjlib.md" },
    { mkmr = "libraries/mkmr.md" },
    { "ml.lib" = "libraries/ml.lib.md" },
    { moocow = "libraries/moocow.md" },
    { moonlib = "libraries/moonlib.md" },
    { motex = "libraries/motex.md" },
    { "mp3cast~" = "libraries/mp3cast~.md" },
    { mpv = "libraries/mpv.md" },
    { mrpeach = "libraries/mrpeach.md" },
    { muug = "libraries/muug.md" },
    { ndi = "libraries/ndi.md" },
    { neuralnet = "libraries/neuralnet.md" },
    { nicinfo = "libraries/nicinfo.md" },
    { nilwind = "libraries/nilwind.md" },
    { notesLib = "libraries/notesLib.md" },
    { nusmuk-audio = "libraries/nusmuk-audio.md" },
    { nusmuk-utils = "libraries/nusmuk-utils.md" },
    { ofelia = "libraries/ofelia.md" },
    { "openscofo~" = "libraries/openscofo~.md" },
    { osc = "libraries/osc.md" },
    { oscx = "libraries/oscx.md" },
    { ossia = "libraries/ossia.md" },
    { "p2p~" = "libraries/p2p~.md" },
    { pan = "libraries/pan.md" },
    { patcherize-plugin = "libraries/patcherize-plugin.md" },
    { pd-psycho = "libraries/pd-psycho.md" },
    { pd-push-and-hold = "libraries/pd-push-and-hold.md" },
    { pd-zmq = "libraries/pd-zmq.md" },
    { pd_protobuf = "libraries/pd_protobuf.md" },
    { pdcontainer = "libraries/pdcontainer.md" },
    { pddp = "libraries/pddp.md" },
    { pdjs = "libraries/pdjs.md" },
    { pdlua = "libraries/pdlua.md" },
    { pdmus = "libraries/pdmus.md" },
    { pdogg = "libraries/pdogg.md" },
    { pdp = "libraries/pdp.md" },
    { pdpii2c = "libraries/pdpii2c.md" },
    { pduino = "libraries/pduino.md" },
    { piro = "libraries/piro.md" },
    { pispi = "libraries/pispi.md" },
    { pix_artoolkit = "libraries/pix_artoolkit.md" },
    { pix_opencv = "libraries/pix_opencv.md" },
    { planifolia = "libraries/planifolia.md" },
    { "plugin~" = "libraries/plugin~.md" },
    { pmpd = "libraries/pmpd.md" },
    { pof = "libraries/pof.md" },
    { pofbeam = "libraries/pofbeam.md" },
    { pool = "libraries/pool.md" },
    { pulqui = "libraries/pulqui.md" },
    { puremapping = "libraries/puremapping.md" },
    { purepd = "libraries/purepd.md" },
    { purest_json = "libraries/purest_json.md" },
    { py4pd = "libraries/py4pd.md" },
    { queryresponse = "libraries/queryresponse.md" },
    { quilt = "libraries/quilt.md" },
    { reactive = "libraries/reactive.md" },
    { rfpg = "libraries/rfpg.md" },
    { rtc = "libraries/rtc.md" },
    { "rtcmix~" = "libraries/rtcmix~.md" },
    { senselmorph = "libraries/senselmorph.md" },
    { sfruit = "libraries/sfruit.md" },
    { shadylib = "libraries/shadylib.md" },
    { shmem = "libraries/shmem.md" },
    { shotnoise = "libraries/shotnoise.md" },
    { sigpack = "libraries/sigpack.md" },
    { simplex = "libraries/simplex.md" },
    { slip = "libraries/slip.md" },
    { smlib = "libraries/smlib.md" },
    { soundhack = "libraries/soundhack.md" },
    { spect_scaled = "libraries/spect_scaled.md" },
    { spring22 = "libraries/spring22.md" },
    { ssr = "libraries/ssr.md" },
    { stash = "libraries/stash.md" },
    { "streamStretch~" = "libraries/streamStretch~.md" },
    { "swe~" = "libraries/swe~.md" },
    { syslog = "libraries/syslog.md" },
    { "tabreceive_mult~" = "libraries/tabreceive_mult~.md" },
    { "tabwrite_dir~" = "libraries/tabwrite_dir~.md" },
    { tclpd = "libraries/tclpd.md" },
    { "tdh.lib" = "libraries/tdh.lib.md" },
    { "tdh.satk" = "libraries/tdh.satk.md" },
    { testtools = "libraries/testtools.md" },
    { timbreIDLib = "libraries/timbreIDLib.md" },
    { timestretch = "libraries/timestretch.md" },
    { tof = "libraries/tof.md" },
    { tracker = "libraries/tracker.md" },
    { triggerize-plugin = "libraries/triggerize-plugin.md" },
    { "tune~" = "libraries/tune~.md" },
    { ultraleap = "libraries/ultraleap.md" },
    { unauthorized = "libraries/unauthorized.md" },
    { unicode = "libraries/unicode.md" },
    { upp = "libraries/upp.md" },
    { vabs = "libraries/vabs.md" },
    { vanilla = "libraries/vanilla.md" },
    { vasp = "libraries/vasp.md" },
    { vbap = "libraries/vbap.md" },
    { "vinylcontrol~" = "libraries/vinylcontrol~.md" },
    { "vstplugin~" = "libraries/vstplugin~.md" },
    { wavview = "libraries/wavview.md" },
    { webserver = "libraries/webserver.md" },
    { websocketserver = "libraries/websocketserver.md" },
    { windowing = "libraries/windowing.md" },
    { witsensor = "libraries/witsensor.md" },
    { ws = "libraries/ws.md" },
    { xlab = "libraries/xlab.md" },
    { xsample = "libraries/xsample.md" },
    { zconf = "libraries/zconf.md" },
    { zexy = "libraries/zexy.md" },
]

[[project.nav]]
Pieces = [
    "pieces/index.md",
    { "Generative Music" = [
    "pieces/generative_music/index.md",
    { "4 pianeti (2018)" = "pieces/generative_music/4_pianeti.md" },
] },
    { Live-Electronics = [
    "pieces/live-electronics/index.md",
    { "Cânticos de Silício I (2025)" = "pieces/live-electronics/cânticos_de_silício_i.md" },
    { "Eco (2022)" = "pieces/live-electronics/eco.md" },
] },
]

[[project.nav]]
Web = [
    { pd4web = "web/pd4web.md" },
    { pdwebparty = "web/pdwebparty.md" },
    { pdxr = "web/pdxr.md" },
    { purrdata = "web/purrdata.md" },
]

[[project.nav]]
Tools = [
    { deken = "deken.md" },
    { pd-lib-builder = "devs/pdlibbuilder.md" },
    { "pd.cmake" = "devs/pd.cmake.md" },
]

[project.markdown_extensions."pymdownx.tabbed"]
alternate_style = true

[project.markdown_extensions."pymdownx.emoji"]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions."pymdownx.extra"]

[project.markdown_extensions."pymdownx.details"]

[project.markdown_extensions."pymdownx.inlinehilite"]

[project.markdown_extensions."pymdownx.tasklist"]

[project.markdown_extensions."pymdownx.magiclink"]

[project.markdown_extensions."pymdownx.highlight"]

[project.markdown_extensions.abbr]

[project.markdown_extensions.admonition]

[project.markdown_extensions.attr_list]

[project.markdown_extensions.md_in_html]

[project.markdown_extensions."pymdownx.superfences"]

[project.markdown_extensions.footnotes]

[project.markdown_extensions."pymdownx.keys"]

[project.markdown_extensions.def_list]
